export const BikeListObject = [
    {
        name: 'BIZON',
        BatteryCapacity: 13,
        numberOfSpeeds: 6,
        wheelSize: 26,
        brakes: 'Дисковые',
        cost: 172500,
        modelYear: 2022,
        power: 500,
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'el_mountain'
    },
    {
        name: 'DUNDEE',
        BatteryCapacity: 10.4,
        numberOfSpeeds: 1,
        wheelSize: 20,
        brakes: 'Ободные',
        cost: 61900,
        modelYear: 2022,
        power: 250,
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'el_city'
    },
    {
        name: 'VOLCANO',
        BatteryCapacity: 10,
        numberOfSpeeds: 6,
        wheelSize: 27.5,
        brakes: 'Дисковые',
        cost: 81100,
        modelYear: 2022,
        power: 250,
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'el_mountain'
    },
    {
        name: 'TIGER PLUS',
        BatteryCapacity: 4,
        wheelSize: 26,
        cost: 34600,
        modelYear: 2022,
        power: 250,
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'el_kick_scooter'
    },





    {
        name: 'BARCELONA',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'mountain'
    },
    {
        name: 'APACHE',
        category: 'Хардтейл',
        numberOfSpeeds: 24,
        wheelSize: 27.5,
        brakes: 'Дисковые гидравлические',
        cost: 34990,
        modelYear: 2021,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'mountain'
    },
    {
        name: 'AZURE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 9190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind'
    },
    {
        name: 'FLARE',
        category: 'Двухподвесы',
        numberOfSpeeds: 9,
        wheelSize: 27.5,
        brakes: 'Дисковые механические',
        cost: 57390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport'
    },
    {
        name: 'DORTMUND',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 28,
        brakes: 'Ножной тормоз',
        cost: 16090,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city'
    },
    {
        name: 'SEVILLA',
        category: 'Городские',
        numberOfSpeeds: 6,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20890,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city'
    },
    {
        name: 'IMPULSE',
        category: 'Туристические',
        numberOfSpeeds: 8,
        wheelSize: 28,
        brakes: 'Дисковые механические',
        cost: 62290,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport'
    },
    {
        name: 'CROCKY',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 10190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind'
    },
    {
        name: 'JAGUAR',
        category: 'Самокаты',
        numberOfSpeeds: '',
        wheelSize: 8.5,
        brakes: '',
        cost: 10191,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'kick_scooter'
    },
    {
        name: 'ZIGZAG',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 20,
        brakes: 'Ободные (U-Brake)',
        cost: 40350,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Некладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX'
    },
    {
        name: 'NEXT',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 22.5,
        brakes: 'Ободные (U-Brake)',
        cost: 45350,
        modelYear: 2020,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX'
    },
    {
        name: 'GRACE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 24,
        brakes: 'Ножной тормоз',
        cost: 18890,
        modelYear: 2020,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'woman'
    },
    {
        name: 'JADE',
        category: 'Хардтейл',
        numberOfSpeeds: 7,
        wheelSize: 24,
        brakes: 'Дисковые механические',
        cost: 30590,
        modelYear: 2022,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'woman'
    },







    {
        name: 'BARCELONA',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'mountain2'
    },
    {
        name: 'APACHE',
        category: 'Хардтейл',
        numberOfSpeeds: 24,
        wheelSize: 27.5,
        brakes: 'Дисковые гидравлические',
        cost: 34990,
        modelYear: 2021,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'mountain2'
    },
    {
        name: 'AZURE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 9190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind2'
    },
    {
        name: 'FLARE',
        category: 'Двухподвесы',
        numberOfSpeeds: 9,
        wheelSize: 27.5,
        brakes: 'Дисковые механические',
        cost: 57390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport2'
    },
    {
        name: 'DORTMUND',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 28,
        brakes: 'Ножной тормоз',
        cost: 16090,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city2'
    },
    {
        name: 'SEVILLA',
        category: 'Городские',
        numberOfSpeeds: 6,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20890,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city2'
    },
    {
        name: 'IMPULSE',
        category: 'Туристические',
        numberOfSpeeds: 8,
        wheelSize: 28,
        brakes: 'Дисковые механические',
        cost: 62290,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport2'
    },
    {
        name: 'CROCKY',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 10190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind2'
    },
    {
        name: 'ZIGZAG',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 20,
        brakes: 'Ободные (U-Brake)',
        cost: 40350,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Некладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX2'
    },
    {
        name: 'NEXT',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 22.5,
        brakes: 'Ободные (U-Brake)',
        cost: 45350,
        modelYear: 2020,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX2'
    },
    {
        name: 'GRACE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 24,
        brakes: 'Ножной тормоз',
        cost: 18890,
        modelYear: 2020,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'woman2'
    },
    {
        name: 'JADE',
        category: 'Хардтейл',
        numberOfSpeeds: 7,
        wheelSize: 24,
        brakes: 'Дисковые механические',
        cost: 30590,
        modelYear: 2022,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'woman2'
    },






    {
        name: 'BARCELONA',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'mountain3'
    },
    {
        name: 'APACHE',
        category: 'Хардтейл',
        numberOfSpeeds: 24,
        wheelSize: 27.5,
        brakes: 'Дисковые гидравлические',
        cost: 34990,
        modelYear: 2021,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'mountain3'
    },
    {
        name: 'AZURE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 9190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind3'
    },
    {
        name: 'FLARE',
        category: 'Двухподвесы',
        numberOfSpeeds: 9,
        wheelSize: 27.5,
        brakes: 'Дисковые механические',
        cost: 57390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport3'
    },
    {
        name: 'DORTMUND',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 28,
        brakes: 'Ножной тормоз',
        cost: 16090,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city3'
    },
    {
        name: 'SEVILLA',
        category: 'Городские',
        numberOfSpeeds: 6,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20890,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city3'
    },
    {
        name: 'IMPULSE',
        category: 'Туристические',
        numberOfSpeeds: 8,
        wheelSize: 28,
        brakes: 'Дисковые механические',
        cost: 62290,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport3'
    },
    {
        name: 'CROCKY',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 10190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind3'
    },
    {
        name: 'ZIGZAG',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 20,
        brakes: 'Ободные (U-Brake)',
        cost: 40350,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Некладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX3'
    },
    {
        name: 'NEXT',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 22.5,
        brakes: 'Ободные (U-Brake)',
        cost: 45350,
        modelYear: 2020,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX3'
    },
    {
        name: 'GRACE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 24,
        brakes: 'Ножной тормоз',
        cost: 18890,
        modelYear: 2020,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'woman3'
    },
    {
        name: 'JADE',
        category: 'Хардтейл',
        numberOfSpeeds: 7,
        wheelSize: 24,
        brakes: 'Дисковые механические',
        cost: 30590,
        modelYear: 2022,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'woman3'
    },





    {
        name: 'BARCELONA',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'mountain4'
    },
    {
        name: 'APACHE',
        category: 'Хардтейл',
        numberOfSpeeds: 24,
        wheelSize: 27.5,
        brakes: 'Дисковые гидравлические',
        cost: 34990,
        modelYear: 2021,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'mountain4'
    },
    {
        name: 'AZURE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 9190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind4'
    },
    {
        name: 'FLARE',
        category: 'Двухподвесы',
        numberOfSpeeds: 9,
        wheelSize: 27.5,
        brakes: 'Дисковые механические',
        cost: 57390,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport4'
    },
    {
        name: 'DORTMUND',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 28,
        brakes: 'Ножной тормоз',
        cost: 16090,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city4'
    },
    {
        name: 'SEVILLA',
        category: 'Городские',
        numberOfSpeeds: 6,
        wheelSize: 26,
        brakes: 'Ободные (V-Brake)',
        cost: 20890,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'city4'
    },
    {
        name: 'IMPULSE',
        category: 'Туристические',
        numberOfSpeeds: 8,
        wheelSize: 28,
        brakes: 'Дисковые механические',
        cost: 62290,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'sport4'
    },
    {
        name: 'CROCKY',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 18,
        brakes: 'Ножной тормоз',
        cost: 10190,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Складная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Детские',
        image: 'kind4'
    },
    {
        name: 'ZIGZAG',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 20,
        brakes: 'Ободные (U-Brake)',
        cost: 40350,
        modelYear: 2022,
        sex: 'Мужской/женский',
        frameType: 'Некладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX4'
    },
    {
        name: 'NEXT',
        category: 'Спортивные',
        numberOfSpeeds: 1,
        wheelSize: 22.5,
        brakes: 'Ободные (U-Brake)',
        cost: 45350,
        modelYear: 2020,
        sex: 'Мужской/женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: '',
        image: 'BMX4'
    },
    {
        name: 'GRACE',
        category: 'Городские',
        numberOfSpeeds: 1,
        wheelSize: 24,
        brakes: 'Ножной тормоз',
        cost: 18890,
        modelYear: 2020,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Сталь Hi-Ten',
        age: 'Взрослые',
        image: 'woman4'
    },
    {
        name: 'JADE',
        category: 'Хардтейл',
        numberOfSpeeds: 7,
        wheelSize: 24,
        brakes: 'Дисковые механические',
        cost: 30590,
        modelYear: 2022,
        sex: 'Женский',
        frameType: 'Нескладная',
        frameMaterial: 'Алюминиевый сплав 6061',
        age: 'Взрослые',
        image: 'woman4'
    }
]
for (let i = 0; i < BikeListObject.length; i++) {
    BikeListObject[i]['id'] = i
}